# Generated by Django 4.1 on 2024-03-13 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_comment_create_date_alter_post_create_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="create_date",
        ),
        migrations.RemoveField(
            model_name="post",
            name="create_date",
        ),
        migrations.AddField(
            model_name="comment",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 13, 10, 22, 11, 295676, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 13, 10, 22, 11, 295676, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
